# Generated by Django 5.1 on 2024-09-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_country_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
